version: "3.9"

services:
  auth:
    build: ./auth
    container_name: auth-service
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"

  event:
    build: ./event
    container_name: event-service
    environment:
      - HOST=0.0.0.0
      - PORT=3002
    ports:
      - "3002:3002"

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - auth
      - event
    environment:
      - PORT=3000
      # Tell gateway where to find the micro-services over the Docker network
      - AUTH_HOST=auth-service
      - AUTH_PORT=3001
      - EVENT_HOST=event-service
      - EVENT_PORT=3002
    ports:
      - "3000:3000"