services:
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"

  event:
    build: 
      context: ./event
      dockerfile: Dockerfile
    container_name: event
    environment:
      - HOST=0.0.0.0
      - PORT=3002
    ports:
      - "3002:3002"

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - auth
      - event
    environment:
      - PORT=3000
      - AUTH_HOST=auth
      - AUTH_PORT=3001
      - EVENT_HOST=event
      - EVENT_PORT=3002
    ports:
      - "3000:3000"